### ISSUE TITLE
big performant issue on this computer

### ISSUE THREAD

**Issue by Gromatou** [yurisuika/Raised#72] opened 2023-11-09 18:18 UTC
https://spark.lucko.me/G3UbXKGHY1
raised is using 40% of the render thread

**Comment by Gromatou** [comment] 2023-11-09 18:18
![image](https://github.com/yurisuika/Raised/assets/117398283/3bacb545-0b14-40d6-a537-c88d9157d070)

**Comment by Gromatou** [comment] 2023-11-09 18:38
without the mod he have 160 fps

**Comment by yurisuika** [comment] 2023-11-10 08:44
duplicate of #61, already fixed in 3.1.0

**Closed by yurisuika** 2023-11-10 08:44 UTC
