### ISSUE TITLE
Incompatible With Farmer's Delight (Fabric 1.20)

### ISSUE THREAD

**Issue by Rebel459** [yurisuika/Raised#54] opened 2023-08-20 07:12 UTC

**Comment by Rebel459** [comment] 2023-08-20 07:12
Affects 1.2.3 and 2.0

**Comment by yurisuika** [comment] 2023-08-23 03:50
Hi, I am not sure what your issue is, would you please be a little more clear?

Raised added support for Farmer's Delight's Comfort and Nourishment overlays in March with version [1.2.2.](https://github.com/yurisuika/Raised/releases/tag/1.2.2)

These were added in November. At the same time, these additions had quickly prompted a PR on Farmer's Delight Fabric [just a day later](https://github.com/newhoryzon/farmers-delight-fabric/commit/219328cd9b0ca998ba61a35317791963971a3f22) to add support for Raised from its end. This PR [was merged in May](https://github.com/newhoryzon/farmers-delight-fabric/pull/106).

However, Raised version [1.2.0.](https://github.com/yurisuika/Raised/releases/tag/1.2.0) which was released in February had already broken this compatibility, as the ObjectShare object was renamed. This has since been reverted (well it now has both the new and old object) with 2.0.0. This sort of worked out, because otherwise compatibility from both ends working at the same time would have resulted in a doubling of the offset.

So, FD releases since May should probably work with Raised 2.0.0. For releases from before then, you'll want to used Raised 1.2.2 or 1.2.3.

I can confirm right now that Raised 2.0.0 works with Farmer's Delight 1.4.1/2 on Minecraft 1.20.1 Fabric.

If this is not your issue, please reopen this and be more specific.

**Closed by yurisuika** 2023-08-23 03:50 UTC
