### ISSUE TITLE
item borders incompatibility with 3.0.0

### ISSUE THREAD

**Issue by vex-ace** [yurisuika/Raised#65] opened 2023-10-13 09:34 UTC
(2.0.0)
![2023-10-13_04 29 26](https://github.com/yurisuika/Raised/assets/133958799/68eb542a-5909-4c42-a813-8e4411927739)
(3.0.0)
![2023-10-13_04 22 13](https://github.com/yurisuika/Raised/assets/133958799/4a3df550-ea5f-4fa2-b151-e64dfc4ead51)

**Comment by yurisuika** [comment] 2023-10-17 11:14
I have one idea on how this might be supported. I can confirm this is on both Forge and Fabric, and 1.19.x does not work either.

It will probably involve adding a "catch" for injections around certain HUD elements. This mod injects AFTER the renderHotbarItem calls in renderHotbar.

**Comment by yurisuika** [comment] 2023-10-17 13:27
I'm not really sure the answer to this one yet. Perhaps it has something to do with its custom Iceberg library. It seems to use that for `drawGradientRect` instead of `fillGradient` from DrawContext or DrawableHelper. That could have something to do with it, my best guess right now.

At the end of the day, this is all stuff that I am unfamiliar with, so my recommendation for now is to just use <=2.x for now.

**Comment by yurisuika** [comment] 2023-10-17 13:31
Okay, I rewrote their mod (never submitted that previous comment so its why its like from a minute before this one) to use the vanilla gradient stuff and that wasn't it. But then I looked around and traced the methods back and bam it hit me like how did I not notice that before.

![image](https://github.com/yurisuika/Raised/assets/7410303/11feeb2b-814b-474b-8ac4-d4a3b5ad1bcd)
So it doesn't use the stack for the hotbar. I don't know why, but that is the source of the issue here. It is creating a new stack. If you were to make it use the stack (like I did in that screenshot), it would work. This would have to be fixed on their end.

![image](https://github.com/yurisuika/Raised/assets/7410303/46e2c527-3a03-4abf-9982-55ab8504207c)

**Closed by yurisuika** 2023-10-17 13:31 UTC

**Comment by yurisuika** [comment] 2023-10-17 13:46
The reason this is not an issue with 2.x or earlier is because Raised worked differently back then. Raised modified the Y value which was inherited down the line all the way to the hotbar item's render method which this mod took its Y value from. Now Raised translates the matrix stacks instead. This mod does not use the stack for the hotbar for some reason. The two ways cannot be done at the same time or else it would just double the vanilla stuff.
