### ISSUE TITLE
1.19.2 Compatibility with Armor Points ++

### ISSUE THREAD

**Issue by slinkybass** [yurisuika/Raised#33] opened 2023-02-21 17:36 UTC
Using:
- Minecraft 1.19.2
- Fabric 0.14.14
- raised-fabric-1.19.2-1.2.1.jar
- armorpointspp-fabric-1.19.2-3.0.9.jar

With raised-fabric-1.19.2-1.1.4.jar works fine.

[crash-2023-02-21_18.31.32-client.txt](https://github.com/yurisuika/Raised/files/10796067/crash-2023-02-21_18.31.32-client.txt)

**Comment by yurisuika** [comment] 2023-02-22 15:33
This is a duplicate of #30.

**Closed by yurisuika** 2023-02-22 15:33 UTC
